[package]
name = "gimbal_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
pest = "2.0"
pest_derive = "2.0"
yaml-rust = "0.4"
postgres = "0.19"
